FROM php:7.4-fpm

WORKDIR /var/www/html

RUN apt-get update \
  &&  apt-get install --quiet --yes --no-install-recommends \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    unzip \
  && docker-php-ext-install zip pdo pdo_mysql \
  && pecl install -o -f redis-5.1.1 \
  && docker-php-ext-enable redis \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd

COPY --from=composer /usr/bin/composer /usr/bin/composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN curl -s https://getcomposer.org/composer.phar > /usr/local/bin/composer \
#   && chmod a+x /usr/local/bin/composer

# RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
#   && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
#   # Make sure we're installing what we think we're installing!
#   && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
#   && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot \
#   && rm -f /tmp/composer-setup.*

# WORKDIR /var/www/html
# RUN composer update

RUN groupadd --gid 1000 appuser \
  && useradd --uid 1000 -g appuser \
    -G www-data,root --shell /bin/bash \
    --create-home appuser

USER appuser