version: "3"

services:
  app:
    container_name: app
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      # - /var/www/html/vendor
      - ./src:/var/www/html
    networks:
      - laravel_react

  node:
    container_name: node
    image: node:14-alpine
    user: node
    working_dir: /assets
    volumes:
      - ./src:/assets
    command: npm run watch
    networks:
      - laravel_react

  web:
    container_name: web
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
    depends_on:
      - app
      - node
    networks:
      - laravel_react

  mail:
    container_name: mail
    image: mailhog/mailhog
    ports:
      # 1025 that is mapped to the localhost port 8003 on the local host is the mail server IMAP port that the application sends emails to.
      # port 8025 that is mapped to the local host port 8100 is a web dashboard http port
      - "8003:1025"
      - "8100:8025"
    networks:
      - laravel_react


networks:
  laravel_react:
    driver: bridge